services:
  django-pokemon-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=your-secret-key
      - DEBUG=True
      - SUPERUSER_USERNAME=bbecerra
      - SUPERUSER_PASSWORD=becerra123
      - SUPERUSER_EMAIL=byron.becerra.aravena@gmail.com
    
    command: ["sh", "entrypoint.sh"]