services:
  web:
    build: .
    volumes:
      - .:/app  # Monta todo el proyecto (incluye tu base de datos)
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=django-insecure-1z9m$@l0)k!9j^u7@4w2+f5l8t3t5$!fxti&2p-z00=0g+@pmp
      - DEBUG=True
      - SUPERUSER_USERNAME=bbecerra
      - SUPERUSER_PASSWORD=becerra123
      - SUPERUSER_EMAIL=byron.becerra.aravena@gmail.com
    command: ["sh", "-c", "python manage.py migrate && python create_superuser.py && python manage.py runserver 0.0.0.0:8000"]
